# Generated by Django 5.0.2 on 2024-03-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
